
package Forms;

import mainframes.*;
import classes.*;

import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class LibrarianForm extends javax.swing.JFrame {
       int noMoreTable = 0;
     String fullName, gender, address, password,shift;
     int contactNo;
    
    public LibrarianForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    public void getLibrarianInfo(String name,String gender, String address, int contact, String shift){
         fullNameTxt.setText(name);
         if(gender.equals("Male")){
             maleRdo.setSelected(true);
         }else{
             femaleRdo.setSelected(true);
         }
         addressTxt.setText(address);
         contactNoTxt.setText(Integer.toString(contact));
         
         
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        newLibrarianPanel1 = new javax.swing.JPanel();
        newLibrarianPanel2 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        fullNameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        contactNoLabel = new javax.swing.JLabel();
        contactNoTxt = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        recordBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        shiftLabel = new javax.swing.JLabel();
        monBox = new javax.swing.JCheckBox();
        tueBox = new javax.swing.JCheckBox();
        wedBox = new javax.swing.JCheckBox();
        thuBox = new javax.swing.JCheckBox();
        friBox = new javax.swing.JCheckBox();
        satBox = new javax.swing.JCheckBox();
        sunBox = new javax.swing.JCheckBox();
        genderLable = new javax.swing.JLabel();
        maleRdo = new javax.swing.JRadioButton();
        femaleRdo = new javax.swing.JRadioButton();
        updateBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        librarianTitle = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Librarian");
        setPreferredSize(new java.awt.Dimension(380, 580));
        setResizable(false);

        newLibrarianPanel1.setBackground(new java.awt.Color(51, 51, 51));
        newLibrarianPanel1.setPreferredSize(new java.awt.Dimension(375, 545));

        newLibrarianPanel2.setBackground(new java.awt.Color(25, 180, 156));
        newLibrarianPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Librarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Demi Cond", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        newLibrarianPanel2.setForeground(new java.awt.Color(255, 255, 255));
        newLibrarianPanel2.setPreferredSize(new java.awt.Dimension(337, 385));

        nameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Full Name:");

        fullNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTxtActionPerformed(evt);
            }
        });

        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(255, 255, 255));
        addressLabel.setText("Address:");

        contactNoLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        contactNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactNoLabel.setText("Contact No:");

        contactNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoTxtActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        recordBtn.setBackground(new java.awt.Color(0, 51, 51));
        recordBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        recordBtn.setForeground(new java.awt.Color(255, 255, 255));
        recordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/record.png"))); // NOI18N
        recordBtn.setText("Record");
        recordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(204, 0, 0));
        clearBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/cleaner.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setToolTipText("");

        shiftLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        shiftLabel.setForeground(new java.awt.Color(255, 255, 255));
        shiftLabel.setText("Shift:");

        monBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        monBox.setForeground(new java.awt.Color(255, 255, 255));
        monBox.setText("Monday");

        tueBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tueBox.setForeground(new java.awt.Color(255, 255, 255));
        tueBox.setText("Tuesday");

        wedBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wedBox.setForeground(new java.awt.Color(255, 255, 255));
        wedBox.setText("Wednesday");

        thuBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        thuBox.setForeground(new java.awt.Color(255, 255, 255));
        thuBox.setText("Thursday");

        friBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        friBox.setForeground(new java.awt.Color(255, 255, 255));
        friBox.setText("Friday");

        satBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        satBox.setForeground(new java.awt.Color(255, 255, 255));
        satBox.setText("Saturday");

        sunBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sunBox.setForeground(new java.awt.Color(255, 255, 255));
        sunBox.setText("Sunday");

        genderLable.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        genderLable.setForeground(new java.awt.Color(255, 255, 255));
        genderLable.setText("Gender:");

        genderGroup.add(maleRdo);
        maleRdo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        maleRdo.setForeground(new java.awt.Color(255, 255, 255));
        maleRdo.setText("Male");
        maleRdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRdoActionPerformed(evt);
            }
        });

        genderGroup.add(femaleRdo);
        femaleRdo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        femaleRdo.setForeground(new java.awt.Color(255, 255, 255));
        femaleRdo.setText("female");
        femaleRdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRdoActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 51, 51));
        updateBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/record.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newLibrarianPanel2Layout = new javax.swing.GroupLayout(newLibrarianPanel2);
        newLibrarianPanel2.setLayout(newLibrarianPanel2Layout);
        newLibrarianPanel2Layout.setHorizontalGroup(
            newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                        .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(genderLable)
                                    .addComponent(nameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maleRdo)
                                    .addComponent(femaleRdo)
                                    .addComponent(fullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                                        .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(addressLabel)
                                            .addComponent(contactNoLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addressTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                            .addComponent(contactNoTxt)))
                                    .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(shiftLabel)
                                            .addComponent(passwordLabel))
                                        .addGap(9, 9, 9)
                                        .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                                                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(monBox)
                                                    .addComponent(tueBox)
                                                    .addComponent(wedBox)
                                                    .addComponent(thuBox))
                                                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(satBox)
                                                            .addComponent(friBox)))
                                                    .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(sunBox))))
                                            .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(recordBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(updateBtn)))))))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newLibrarianPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearBtn)))
                .addContainerGap())
        );
        newLibrarianPanel2Layout.setVerticalGroup(
            newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newLibrarianPanel2Layout.createSequentialGroup()
                .addComponent(clearBtn)
                .addGap(22, 22, 22)
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(fullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLable)
                    .addComponent(maleRdo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(femaleRdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNoLabel)
                    .addComponent(contactNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monBox)
                    .addComponent(friBox)
                    .addComponent(shiftLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satBox)
                    .addComponent(tueBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wedBox)
                    .addComponent(sunBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thuBox)
                .addGap(18, 18, 18)
                .addGroup(newLibrarianPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordBtn)
                    .addComponent(updateBtn))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(25, 180, 156));

        librarianTitle.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        librarianTitle.setForeground(new java.awt.Color(255, 255, 255));
        librarianTitle.setText("<html><u>Librarian Form</u></html>");

        backBtn.setBackground(new java.awt.Color(25, 180, 156));
        backBtn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/backward.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(librarianTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(librarianTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout newLibrarianPanel1Layout = new javax.swing.GroupLayout(newLibrarianPanel1);
        newLibrarianPanel1.setLayout(newLibrarianPanel1Layout);
        newLibrarianPanel1Layout.setHorizontalGroup(
            newLibrarianPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newLibrarianPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newLibrarianPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newLibrarianPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addContainerGap())
        );
        newLibrarianPanel1Layout.setVerticalGroup(
            newLibrarianPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newLibrarianPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newLibrarianPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newLibrarianPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newLibrarianPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTxtActionPerformed

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void contactNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNoTxtActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void recordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtnActionPerformed
        // record librarian info
            
        
        fullName = fullNameTxt.getText();
        
            if(maleRdo.isSelected()){
                gender = "Male";
            }else{
                gender = "Female";
            }
        address = addressTxt.getText();
        contactNo = Integer.parseInt(contactNoTxt.getText());
        password = new String(passwordField.getPassword());
        shift = "";
        
        if(monBox.isSelected()){
            shift += "Mon";
        }
        if(tueBox.isSelected()){
            shift += ",Tue";
        }
        if(wedBox.isSelected()){
            shift += ",Wed";
        }
        if(thuBox.isSelected()){
            shift += ",Thu";
        }
        if(friBox.isSelected()){
            shift += ",Fri";
        }
        if(satBox.isSelected()){
            shift += ",Sat";
        }
        if(sunBox.isSelected()){
            shift += ",Sun";
        }
        
        Librarian info = new Librarian();//object creation
        info.addLibrarianInfo(password,shift);//passing to method in librarian
        info.setInfo(fullName, gender, address, contactNo);//passing to method in person
        if(noMoreTable == 0 ){//createing table once
        
        }
        info.register(info);
        
        noMoreTable = 1;

        int ok = 0;
        JOptionPane.showMessageDialog(this, "Your Data is Successfully Recorded!", "Data Recorded",JOptionPane.INFORMATION_MESSAGE);
        if(ok == 0){
            AdminMain admin = new AdminMain();
            admin.setVisible(true);
            
            dispose();
            
        }
    }//GEN-LAST:event_recordBtnActionPerformed

    private void maleRdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRdoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRdoActionPerformed

    private void femaleRdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRdoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRdoActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // update
        Librarian info = new Librarian();//object creation
         fullName = fullNameTxt.getText();
        
            if(maleRdo.isSelected()){
                gender = "Male";
            }else{
                gender = "Female";
            }
        address = addressTxt.getText();
        contactNo = Integer.parseInt(contactNoTxt.getText());
        
         info.setInfo(fullName, gender, address, contactNo);//passing to method in person
         info.update(info);
         
        int ok = 0;
        JOptionPane.showMessageDialog(this, "Your Data is Successfully Updated!", "Data Updated",JOptionPane.INFORMATION_MESSAGE);
        AdminMain admin = new AdminMain();
        if(ok == 0){
            
            admin.setVisible(true);
            dispose();
           
        }
        admin.rdo().doClick();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // go Backward
        dispose();
        LibrarianMain m = new LibrarianMain();
        m.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Librarian(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel contactNoLabel;
    private javax.swing.JTextField contactNoTxt;
    private javax.swing.JRadioButton femaleRdo;
    private javax.swing.JCheckBox friBox;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel genderLable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel librarianTitle;
    private javax.swing.JRadioButton maleRdo;
    private javax.swing.JCheckBox monBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel newLibrarianPanel1;
    private javax.swing.JPanel newLibrarianPanel2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton recordBtn;
    private javax.swing.JCheckBox satBox;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JCheckBox sunBox;
    private javax.swing.JCheckBox thuBox;
    private javax.swing.JCheckBox tueBox;
    private javax.swing.JButton updateBtn;
    private javax.swing.JCheckBox wedBox;
    // End of variables declaration//GEN-END:variables
}
