
package Forms;

import classes.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import mainframes.*;
import org.jdesktop.swingx.JXDatePicker;

public class MemberForm extends javax.swing.JFrame {

    private String fullName;
    private String gender;
    private int contactNo;
    private String address;
    private int id;
    private String major="";
    private String expire;
    
    
    public MemberForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void getData(){
        fullName = fullNameTxt.getText();
        if(maleRdo.isSelected()){
            gender = "male";
        }else{
            gender = "female";
        }
        
        if(majorCombo.getSelectedIndex() != -1){
            major = majorCombo.getSelectedItem().toString();
        }
        
        contactNo = Integer.parseInt(contactTxt.getText());
        
        address = addressTxt.getText();
        id = Integer.parseInt(memberIdTxt.getText());
      
        
        Date oDate =  expireDate.getDate();
        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        expire = oDateFormat.format(oDate);
    }

    public void setData(String fullName, String gender, String address, int contactNo,int id,String major,String expireDate ){
        
        fullNameTxt.setText(fullName);
        if(gender.equals("male")){
            maleRdo.setSelected(true);
        }else{
            femaleRdo.setSelected(true);
        }
        contactTxt.setText(Integer.toString(contactNo));
        
        addressTxt.setText(address);
        memberIdTxt.setText(Integer.toString(id));
        
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        genderGroup = new javax.swing.ButtonGroup();
        newMemberPanel1 = new javax.swing.JPanel();
        newMemberPanel2 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        maleRdo = new javax.swing.JRadioButton();
        femaleRdo = new javax.swing.JRadioButton();
        majorLabel = new javax.swing.JLabel();
        majorCombo = new javax.swing.JComboBox<>();
        fullNameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        contactTxt = new javax.swing.JTextField();
        contactLabel1 = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        recordBtn = new javax.swing.JButton();
        memberId = new javax.swing.JLabel();
        memberIdTxt = new javax.swing.JTextField();
        expireDate = new org.jdesktop.swingx.JXDatePicker();
        clearBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        memberTitle = new javax.swing.JLabel();
        backBtn7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Member");

        newMemberPanel1.setBackground(new java.awt.Color(51, 51, 51));

        newMemberPanel2.setBackground(new java.awt.Color(25, 180, 156));
        newMemberPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Member", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Demi Cond", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        nameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Full Name:");

        genderLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender:");

        genderGroup.add(maleRdo);
        maleRdo.setForeground(new java.awt.Color(255, 255, 255));
        maleRdo.setText("Male");
        maleRdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRdoActionPerformed(evt);
            }
        });

        genderGroup.add(femaleRdo);
        femaleRdo.setForeground(new java.awt.Color(255, 255, 255));
        femaleRdo.setText("female");
        femaleRdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRdoActionPerformed(evt);
            }
        });

        majorLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        majorLabel.setForeground(new java.awt.Color(255, 255, 255));
        majorLabel.setText("Major:");

        majorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Computer Enginerring", "Accounting & Finance", "TVET" }));

        contactLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        contactLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactLabel.setText("Contact:");

        contactLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        contactLabel1.setForeground(new java.awt.Color(255, 255, 255));
        contactLabel1.setText("Expire Date:");

        addressLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(255, 255, 255));
        addressLabel.setText("Address");

        recordBtn.setBackground(new java.awt.Color(0, 51, 51));
        recordBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        recordBtn.setForeground(new java.awt.Color(255, 255, 255));
        recordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/record.png"))); // NOI18N
        recordBtn.setText("Record");
        recordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtnActionPerformed(evt);
            }
        });

        memberId.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        memberId.setForeground(new java.awt.Color(255, 255, 255));
        memberId.setText("Member Id:");

        memberIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberIdTxtActionPerformed(evt);
            }
        });

        expireDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expireDateActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(204, 0, 0));
        clearBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/cleaner.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setToolTipText("");
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 51, 51));
        updateBtn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/record.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newMemberPanel2Layout = new javax.swing.GroupLayout(newMemberPanel2);
        newMemberPanel2.setLayout(newMemberPanel2Layout);
        newMemberPanel2Layout.setHorizontalGroup(
            newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newMemberPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(memberId)
                    .addComponent(genderLabel)
                    .addComponent(nameLabel)
                    .addComponent(majorLabel)
                    .addComponent(contactLabel)
                    .addComponent(contactLabel1)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fullNameTxt)
                        .addComponent(majorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(femaleRdo)
                        .addComponent(maleRdo)
                        .addComponent(contactTxt)
                        .addComponent(addressTxt)
                        .addComponent(expireDate, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addComponent(memberIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newMemberPanel2Layout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newMemberPanel2Layout.createSequentialGroup()
                        .addComponent(recordBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBtn)
                        .addGap(28, 28, 28))
                    .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        newMemberPanel2Layout.setVerticalGroup(
            newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newMemberPanel2Layout.createSequentialGroup()
                .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberId)
                    .addComponent(memberIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(fullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(maleRdo))
                .addGap(1, 1, 1)
                .addComponent(femaleRdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorLabel)
                    .addComponent(majorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel1)
                    .addComponent(expireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newMemberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordBtn)
                    .addComponent(updateBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(25, 180, 156));

        memberTitle.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        memberTitle.setForeground(new java.awt.Color(255, 255, 255));
        memberTitle.setText("<html><u>Member Form</u></html>");

        backBtn7.setBackground(new java.awt.Color(25, 180, 156));
        backBtn7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        backBtn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/backward.png"))); // NOI18N
        backBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(backBtn7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(memberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memberTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn7, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout newMemberPanel1Layout = new javax.swing.GroupLayout(newMemberPanel1);
        newMemberPanel1.setLayout(newMemberPanel1Layout);
        newMemberPanel1Layout.setHorizontalGroup(
            newMemberPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newMemberPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newMemberPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newMemberPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        newMemberPanel1Layout.setVerticalGroup(
            newMemberPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newMemberPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newMemberPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newMemberPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newMemberPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleRdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRdoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRdoActionPerformed

    private void femaleRdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRdoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRdoActionPerformed

    private void expireDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expireDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expireDateActionPerformed

    private void recordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtnActionPerformed
        
        getData();
        LibraryMember info = new LibraryMember();
        info.setInfo(fullName, gender, address, contactNo);
        info.addMemberInfo(id, major, expire);
        info.register(info);
        
     
        
         int ok = 0;
        JOptionPane.showMessageDialog(this, "Your Data is Successfully Recorded!", "Data Recorded",JOptionPane.INFORMATION_MESSAGE);
        if(ok == 0){
            //to return to dashboard
          LibrarianMain lab = new LibrarianMain();
        lab.setVisible(true);
        lab.dashboard().setSelectedIndex(1);
            dispose();
        }
    }//GEN-LAST:event_recordBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        //update database
        getData();
        LibraryMember info = new LibraryMember();
        info.setInfo(fullName, gender, address, contactNo);
        info.addMemberInfo(id, major, expire);
        info.update(info);
        
       
         int ok = 0;
        JOptionPane.showMessageDialog(this, "Your Data is Successfully Updated!", "Data Recorded",JOptionPane.INFORMATION_MESSAGE);
        if(ok == 0){
            //to return to the main dashboard
        LibrarianMain lab = new LibrarianMain();
        lab.setVisible(true);
        lab.dashboard().setSelectedIndex(1);
        lab.rdo2().doClick();
        
            dispose();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // return everything to default
        
        memberIdTxt.setText("");
        fullNameTxt.setText("");
        maleRdo.setSelected(false);
        femaleRdo.setSelected(false);
        majorCombo.setSelectedIndex(0);
        contactTxt.setText("");
//        expireDate.c
        addressTxt.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void backBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn7ActionPerformed
        // go Backward
        dispose();
        LibrarianMain m = new LibrarianMain();
        m.setVisible(true);
    }//GEN-LAST:event_backBtn7ActionPerformed

    private void memberIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberIdTxtActionPerformed
      
        
    }//GEN-LAST:event_memberIdTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public void member() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton backBtn7;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel contactLabel1;
    private javax.swing.JTextField contactTxt;
    private org.jdesktop.swingx.JXDatePicker expireDate;
    private javax.swing.JRadioButton femaleRdo;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> majorCombo;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JRadioButton maleRdo;
    private javax.swing.JLabel memberId;
    private javax.swing.JTextField memberIdTxt;
    private javax.swing.JLabel memberTitle;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel newMemberPanel1;
    private javax.swing.JPanel newMemberPanel2;
    private javax.swing.JButton recordBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
